# 
#                                 __                 __
#    __  ______  ____ ___  ____ _/ /____  ____  ____/ /
#   / / / / __ \/ __ `__ \/ __ `/ __/ _ \/ __ \/ __  /
#  / /_/ / /_/ / / / / / / /_/ / /_/  __/ /_/ / /_/ /
#  \__, /\____/_/ /_/ /_/\__,_/\__/\___/\____/\__,_/
# /____                     matthewdavis.io, holla!
#
#
#
# https://github.com/kubernetes-incubator/kubespray/blob/master/docs/aws.md 
# https://github.com/kubernetes-incubator/kubespray/tree/master/contrib/aws_iam
# 
- name: Provision AWS IAM Roles & Policies for Kubernetes
  
  #
  # Run these tasks on localhost directly:
  #
  hosts: localhost
  
  #
  # Gather the current configuration from all hosts
  # defined in the inventory file:
  #
  gather_facts: False
  
  #
  # Include variables from configuration files:
  #
  vars_files:
    - vars/aws.yml
    - vars/aws_credentials.yml

  #
  # Execute these tasks by importing their instructions:
  #
  tasks:
    - import_tasks: tasks/aws_00_iam_roles.yml
    - import_tasks: tasks/aws_00_iam_policies.yml