#                                 __                 __
#    __  ______  ____ ___  ____ _/ /____  ____  ____/ /
#   / / / / __ \/ __ `__ \/ __ `/ __/ _ \/ __ \/ __  /
#  / /_/ / /_/ / / / / / / /_/ / /_/  __/ /_/ / /_/ /
#  \__, /\____/_/ /_/ /_/\__,_/\__/\___/\____/\__,_/
# /____                     matthewdavis.io, holla!
#
# 
# https://docs.ansible.com/ansible/latest/modules/ec2_vpc_nat_gateway_module.html
# 
# 
# As you can see, we attach a NAT Gateway to a public subnet.
# This is where the service will be located.
# 
- name: Create new NAT Gateway, using an EIP address  and wait for available status.
  ec2_vpc_nat_gateway:
    region: "{{ aws_region }}"
    subnet_id: "{{ new_subnet_2_id }}"
    state: present
    wait: yes
  register: new_nat_gateway

- name: Set NAT Gateway ID in variable
  set_fact:
    new_nat_gateway_id: "{{ new_nat_gateway.nat_gateway_id }}"  

- name: Tagging NAT Gateway
  ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ new_nat_gateway_id }}"
    state: present
    tags:
      Name: "{{ vpc_name }}-nat-gateway"
      KubernetesCluster: "{{ kubernetes_cluster }}"

- debug: var=new_nat_gateway_id