#                                 __                 __
#    __  ______  ____ ___  ____ _/ /____  ____  ____/ /
#   / / / / __ \/ __ `__ \/ __ `/ __/ _ \/ __ \/ __  /
#  / /_/ / /_/ / / / / / / /_/ / /_/  __/ /_/ / /_/ /
#  \__, /\____/_/ /_/ /_/\__,_/\__/\___/\____/\__,_/
# /____                     matthewdavis.io, holla!
#
#
# Every VPC needs at least one Internet Gateway.
# This component allows traffic between the VPC and the outside world.
# 
- name:               Create Internet Gateway for VPC
  ec2_vpc_igw:
    vpc_id:           "{{ new_vpc_id }}"
    region:           "{{ aws_region }}"
    state:            "present"
  register: my_vpc_igw

- name:               Set Internet Gateway ID in variable
  set_fact:
    new_igw_id:           "{{ my_vpc_igw.gateway_id }}"