
#                                 __                 __
#    __  ______  ____ ___  ____ _/ /____  ____  ____/ /
#   / / / / __ \/ __ `__ \/ __ `/ __/ _ \/ __ \/ __  /
#  / /_/ / /_/ / / / / / / /_/ / /_/  __/ /_/ / /_/ /
#  \__, /\____/_/ /_/ /_/\__,_/\__/\___/\____/\__,_/
# /____                     matthewdavis.io, holla!
#
#
- name: "Terminate instance(s) that were previously launched ({{ instance_ids }})"
  tags:
    - vmdev
  ec2:
    region: "{{ aws_region }}"    
    state: 'absent'
    instance_ids: '{{ instance_ids }}'